apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    svc: product-service
spec:
  type: NodePort
  selector:
    app: product-service
  ports:
    - port: 9002
      targetPort: 9002
      nodePort: 30602
      name: http