apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    svc: user-service
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
    - port: 9001
      targetPort: 9001
      nodePort: 30601
      name: http