server:
  port: 9001

spring:
  profiles:
    active: dev
  application:
    name: user-service

product:
  service:
    name: product-service
    url: ${PRODUCT_SERVICE_ENDPOINT:http://localhost:9002}